/**
 * RASID data spine - canonical TypeScript types.
 *
 * These types are the human-readable source of truth. The JSON Schema files in
 * `schemas/` are the machine-enforced mirror, and `npm run validate` checks the
 * data in `data/` against them. If you change a type here, change the matching
 * schema in the same commit.
 *
 * Honesty rule (spec section 0.2): every field that could be guessed instead of
 * observed carries a `provenance`. Unknown is `null` + `provenance: "unknown"`,
 * never a plausible default.
 */

export type Provenance =
  | "official" // stated on the organisation's own site/announcement
  | "reported" // aggregator site or student reports; treat as approximate
  | "inferred" // derived from past cycles; must be labelled in UI
  | "unknown";

export type Tier = "S" | "A" | "B" | "C";

export type Sector =
  | "gov"
  | "semi_gov"
  | "bank"
  /**
   * DEVIATION FROM SPEC section 3.1: added.
   * Investment houses, brokerages and insurers are not banks. Folding them in
   * blunts the sector filter, and the filter is how the user narrows 116
   * organisations down to the ones worth reading.
   */
  | "finance"
  | "tech"
  | "health"
  | "industrial"
  | "consulting"
  | "startup";

export type SourceType =
  | "careers_page"
  | "announcement_page"
  | "rss"
  | "portal"
  | "email"
  /**
   * DEVIATION FROM SPEC section 3.1: added.
   * A bare homepage, with no careers or training path known yet. Most of the
   * COOP-PDF import is this. Calling a site root a "careers_page" would be the
   * quiet kind of lie this project is built to avoid.
   */
  | "site_root";

/**
 * Where a record came into the database. Kept so that a verified record and an
 * imported one can never be confused in a report.
 */
export type ImportSource =
  | "spec" // the original RASID build specification
  | "coop_pdf_2021" // the circulated COOP directory pdf, ~2020-2021, unverified
  | "manual" // added by hand during a session, with a stated reason
  | null;

export type ApplyMethod = "portal" | "email" | "hrdf" | "linkedin_manual";

/**
 * Every stored link carries how we came to believe in it.
 *
 * A URL is never generated by analogy. `example.com/careers` working is not
 * evidence that `other.com/careers` exists. Only two provenances are legal
 * here, and "inferred" is deliberately not one of them:
 *
 *   "official" - the page was opened and read, and it is what it claims to be.
 *                Requires `verifiedAtISO` and `verifiedNote`.
 *   "reported" - a lead taken from a document or a third party, never opened.
 *                `verifiedAtISO` stays null and the pipeline skips it.
 */
export type LinkProvenance =
  /** The page was opened and read, and it is what it claims to be. */
  | "official"
  /** A lead from a document or a third party. Never opened. */
  | "reported"
  /**
   * An email address, not a page. There is nothing to open, so it can never
   * become "official" and it is permanently reported-strength. It is excluded
   * from the manualCheckUrl count and the fetch pipeline never touches it.
   * Legal in `applyVia` only.
   */
  | "email_channel";

export interface VerifiedLink {
  url: string;
  /**
   * "email_channel" is structurally excluded here, not merely discouraged:
   * only `applyVia` can hold one, so a mail address can never leak into a
   * fetchable source or into the link the user taps.
   */
  provenance: Exclude<LinkProvenance, "email_channel">;
  /** When the page was actually opened and read. null means never opened. */
  verifiedAtISO: string | null;
  /**
   * What was seen there. Required once verified, and it must carry the page's
   * real title plus a phrase read on the page. Without both, the link is
   * "reported", not "official".
   */
  verifiedNote?: string;
}

/**
 * How a source has to be fetched to yield text.
 *
 * "static"  - plain HTTP. The default, and the only mode a source may hold
 *             without someone deciding otherwise.
 * "browser" - rendered in headless Chromium because the page paints itself
 *             with JavaScript and static extraction provably returns nothing.
 *
 * Nothing is promoted to "browser" automatically. A source earns it only after
 * a static run has demonstrably failed on it, and the total is capped
 * (MAX_BROWSER_SOURCES): if more than a handful need a browser, the problem is
 * the choice of sources, not the fetcher.
 */
export type RenderMode = "static" | "browser";

export interface Source extends VerifiedLink {
  type: SourceType;
  checkFrequencyHours: number;
  renderMode: RenderMode;
  /**
   * Try the browser path again in CI, and only there.
   *
   * Set on a source whose rendering failed for want of machine resources
   * rather than for any reason on the site's side: a runner container is
   * roomier than a laptop, so the same page may well render there. A success
   * in CI promotes the source to "browser" for good and writes down why.
   */
  browserRetryInCI?: boolean;
  /** Why renderMode is not the default, in one line. Written by the collector. */
  renderModeNote?: string;
}

/**
 * Spec deviation, deliberate.
 *
 * This was 8, written when collection ran on a cloud runner where every
 * browser launch cost a minute of somebody's quota. Collection now runs on the
 * owner's own machine, because many Saudi government sites refuse a US
 * address, and there Chromium is already installed and the run is unattended.
 * The cap still exists so the browser stays a decision rather than a default,
 * but it is no longer priced as if it were rare.
 */
export const MAX_BROWSER_SOURCES = 30;

/** Thin and unchanged for this many runs is worth surfacing. ~10 days at 6h. */
export const SILENT_THIN_RUNS = 40;

/** Below this the extract is suspiciously short, though still usable. */
export const THIN_CHARS = 200;

export interface ApplyVia {
  method: ApplyMethod;
  /** URL or email address. */
  target: string;
  /** `email_channel` whenever method is "email", and only then. */
  provenance: LinkProvenance;
  /** When the channel was confirmed at its source. Always null for email. */
  verifiedAtISO: string | null;
  note?: string;
}

export interface HistoricalWindow {
  /** e.g. "الفصل الثاني 1447" */
  seasonLabel: string;
  openedISO: string | null;
  closedISO: string | null;
  provenance: Provenance;
}

export interface ZeroCoursesRule {
  /** null = the organisation has never published a rule either way. */
  value: true | false | null;
  provenance: Provenance;
  /** Exact published wording. Required whenever value === true. */
  quote?: string;
  sourceUrl?: string;
}

export interface Stipend {
  amountSAR: number | null;
  provenance: Provenance;
  note?: string;
}

export interface Organisation {
  /** slug, e.g. "sdaia" */
  id: string;
  nameAr: string;
  nameEn: string;
  sector: Sector;
  /** ["الرياض"] etc. Empty = nationwide/unknown. */
  city: string[];
  tier: Tier;

  // THE THREE DECISION FIELDS
  requiresZeroCourses: ZeroCoursesRule;
  /** CS / cybersecurity / IT present in the published major list. */
  acceptsUserMajor: boolean | null;
  /** HRDF product is "التدريب التعاوني", not "تطوير الخريجين". */
  offersCoopProduct: boolean | null;

  // SUPPORTING
  stipend: Stipend;
  flexibility: "high" | "medium" | "low" | "unknown";
  intakeSize: "large" | "medium" | "small" | "unknown";
  /** How much you actually learn. 1-5, or null when unrated. */
  trainingQuality: 1 | 2 | 3 | 4 | 5 | null;

  // SOURCES
  sources: Source[];

  /**
   * DEVIATION FROM SPEC section 3.1: nullable.
   * The spec types this as a required `ApplyVia`, but section 4 forbids
   * inventing values for unverified fields. Most seed organisations have no
   * confirmed application channel yet, so `null` means "not verified" and the
   * validator reports it as coverage debt rather than letting a guessed URL in.
   */
  applyVia: ApplyVia | null;

  /**
   * DEVIATION FROM SPEC section 3.1: nullable, for the same reason as applyVia.
   * One tap for the user to verify manually. When null the UI must say the link
   * is not verified yet - it must not fall back to a search engine guess.
   *
   * This is the link the user personally taps, so it is held to the highest
   * bar in the codebase: it may only ever hold an opened-and-confirmed page.
   * The validator rejects a `reported` lead here, unlike in `sources`.
   */
  manualCheckUrl: VerifiedLink | null;

  // HISTORY (drives prediction, never presented as fact)
  historicalWindows: HistoricalWindow[];

  /** Free text shown in the detail sheet. */
  notes?: string;

  /**
   * Where this record entered the database. Kept so a hand-verified record and
   * a bulk import can never be read as the same thing in a report.
   */
  importSource: ImportSource;
}

/**
 * Aggregators are scanned for *any* co-op announcement and are not
 * organisations, so they live in `data/aggregators.json` with their own shape.
 */
export interface AggregatorSource {
  id: string;
  nameAr: string;
  link: VerifiedLink | null;
  /**
   * Some aggregators are reachable only by writing to a person. The platform
   * can exist and be unpublished, which is exactly the Taif field-training
   * case: the link is requested from the college, not found on the web.
   */
  applyVia: ApplyVia | null;
  /** Ranking hint for the pipeline when the same announcement appears twice. */
  weight: "highest" | "high" | "normal";
  checkFrequencyHours: number;
  note?: string;
}

/**
 * The audit trail of the link-verification rounds, in `data/verification.json`.
 *
 * Negative results are the point of this file. Recording "I looked for SABIC's
 * training page and the careers site has no training section" stops the next
 * round from repeating the search, and it is what makes the counts at the end
 * of `npm run validate` honest: verified, failed, still unknown.
 */
export interface VerificationAttempt {
  /** Organisation or aggregator id. */
  targetId: string;
  checkedAtISO: string;
  /** What was actually opened. null when nothing plausible was found to open. */
  urlTried: string | null;
  outcome:
    | "verified" // opened, and it is a real careers/training page
    | "rejected" // opened, but it is a generic page, not what we need
    | "not_found" // searched, found no candidate page to open at all
    | "unreachable"; // the page would not load: DNS, timeout, block
  /** What was seen, in one line. Required. */
  note: string;
}

export type OpportunityStatus =
  | "open"
  | "closing_soon"
  | "closed"
  | "announced_not_open"
  | "expired"
  /**
   * DEVIATION FROM SPEC section 3.2: added.
   * An announcement that published no dates at all. The spec's five states all
   * assert something about the window, and "open" would be the assertion we
   * have the least right to make: a page can name a programme without ever
   * saying when it takes applications. The home screen must not show this in
   * "مفتوح الآن".
   */
  | "unknown";

export type Product =
  | "coop"
  | "graduate_dev"
  | "professional_experience"
  | "unknown";

export type OpportunityFlag =
  | "few_seats" // seats <= 5
  | "closing_in_48h"
  | "exact_major_match" // cybersecurity / SOC analyst named directly
  | "no_course_condition" // published conditions contain no zero-courses rule
  | "has_stipend"
  | "wrong_product" // it is تطوير الخريجين - user is not eligible yet
  | "first_time_seen" // this org has never posted a co-op before
  | "needs_manual_review"; // classifier failed twice; never drop it silently

export interface Opportunity {
  /** hash of orgId + title + firstSeenISO */
  id: string;
  orgId: string;
  titleAr: string;
  detectedISO: string;
  firstSeenISO: string;
  lastConfirmedISO: string;

  status: OpportunityStatus;

  opensISO: string | null;
  closesISO: string | null;
  /** Umm al-Qura, shown alongside Gregorian. */
  closesHijri: string | null;

  product: Product;
  /** As published. */
  majors: string[];
  seats: number | null;
  stipendSAR: number | null;
  durationWeeks: number | null;
  cities: string[];

  /** 0-100. null only when classification failed and the record is queued. */
  relevanceScore: number | null;
  /** One Arabic sentence, from the classifier. */
  relevanceReason: string;

  /**
   * DEVIATION FROM SPEC section 3.2: added, and the most consequential field
   * in the record for this user.
   *
   * The classifier already extracts whether the page states a zero-courses or
   * full-time condition, and the exact wording behind it. The spec's
   * Opportunity had nowhere to keep either, so both were being thrown away -
   * leaving the one rule that decides whether he can take the placement as an
   * opinion rather than a quote. Kept here so a disagreement about a phrase
   * like "انتظام كلي" is settled by reading the sentence.
   */
  statesZeroCoursesRule: boolean;
  /** The exact published wording. null when no such rule was stated. */
  zeroCoursesQuote: string | null;
  flags: OpportunityFlag[];

  sourceUrl: string;
  applyUrl: string | null;
  /** <= 400 chars, for the user to read himself. */
  rawExcerpt: string;
}

export type HealthState = "healthy" | "degraded" | "broken";

/**
 * What the last successful fetch of a source looked like, in
 * `data/snapshots.json`.
 *
 * Spec section 5.2 hashes the extracted main text so the classifier only sees a
 * page when it has actually changed. Committing the hash to git also answers a
 * question logs cannot: when did this page last change, and how often does it?
 * `lastChangedISO` is the honest basis for predicting a window, in place of the
 * guesswork the UI is forbidden to present as fact.
 */
export interface SourceSnapshot {
  sourceUrl: string;
  orgId: string;
  /** SHA-256 of the extracted main text. null until a fetch succeeds. */
  contentHash: string | null;
  extractedChars: number | null;
  /** Readability, or the noisier stripped-body fallback. Readers should know. */
  extractionMethod: "readability" | "body_fallback" | null;
  firstSeenISO: string;
  /** When the hash last differed from the stored one. */
  lastChangedISO: string | null;
  /**
   * Consecutive runs where the extract was thin AND the hash did not move.
   *
   * A thin source that also goes silent may be a page we are not really
   * reading. It may equally be a training page with nothing on it, which is
   * the normal state outside an application window. At a six-hour cron,
   * SILENT_THIN_RUNS is about ten days: long enough that the quiet is worth
   * a look, and it stays a warning, because CI should fail on broken code and
   * not on an external site having nothing to say.
   */
  thinRuns: number;
  /**
   * The classifier could not judge this text and the source is still owed a
   * verdict. The hash is kept, so a later change is still detectable, but the
   * next run classifies it again instead of skipping it as unchanged. Without
   * this, one failed call would bury a source until the page happened to move.
   */
  pendingClassification: boolean;
}

export interface SourceHealth {
  sourceUrl: string;
  orgId: string;
  lastAttemptISO: string;
  lastSuccessISO: string | null;
  consecutiveFailures: number;
  lastError: string | null;
  /**
   * DEVIATION FROM SPEC section 3.3, on the owner's instruction: the spec put
   * degraded at >1 failure, which showed a source that had already failed once
   * as green. Any failure is now degraded; >5 is still broken.
   */
  state: HealthState;
}
